Feature/bd dfy
The-Gym-Group/TheGymGroup.Core.API.Integration.Tests pull request #6
Opened 2023-01-06 13:50 UTC by raygher

2023-01-06 14:24 UTC, scottyearsley commented on Integration.Tests/IntegrationTests/Tests/CoreAPI/Member/MembersDataIntegrationTests.cs
> +        public async Task GetMemberPaymentHistory_ReturnsData()
These methods can be void - they don't have any async code

2023-01-06 14:24 UTC, scottyearsley commented on Integration.Tests/IntegrationTests/Tests/CoreAPI/Member/MembersDataIntegrationTests.cs
> +        private void IHaveAnInvalidCMember()
Unused method here

2023-01-06 14:26 UTC, scottyearsley commented on Integration.Tests/IntegrationTests/Tests/CoreAPI/Member/MembersDataIntegrationTests.cs
>      [TestFixture]
We are using XUnit and FluentAssertions libs in API code, might be best to standardize here

2023-01-06 14:28 UTC, scottyearsley commented on Integration.Tests/IntegrationTests/Tests/CoreAPI/Member/MembersDataIntegrationTests.cs
>  using Framework.Shared.Objects.CoreAPI.Member;
There are 36 warnings in this file when I open it in Jetbrains Rider - I seem to remember you use VS

2023-01-06 14:37 UTC, scottyearsley requested changes
Sorry - didn't bundle all my comments into a single review

2023-01-06 14:37 UTC, scottyearsley commented on Integration.Tests/IntegrationTests/Tests/CoreAPI/Member/MembersDataIntegrationTests.cs
> +using Microsoft.AspNetCore.Authentication;
Some unneeded usings here

2023-01-06 15:09 UTC, raygher commented on Integration.Tests/IntegrationTests/Tests/CoreAPI/Member/MembersDataIntegrationTests.cs
>  using Framework.Shared.Objects.CoreAPI.Member;
nope, 14. Mostl related to private variables being nullable, which wouldn't be the case.

2023-01-11 13:05 UTC, raygher commented on Integration.Tests/IntegrationTests/Tests/CoreAPI/Member/MembersDataIntegrationTests.cs
>      [TestFixture]
I'm going to need more info on that.

2023-01-16 11:03 UTC, scottyearsley approved these changes

2023-01-16 11:48 UTC, AButler requested changes
I think the warnings can be cleaned up properly rather than just ignoring them. Shouldn't be too much of a refactor.

2023-01-16 11:48 UTC, AButler commented on Integration.Tests/Framework/Properties/Constants/ApiServerConfiguration.cs
> +﻿// ReSharper disable InconsistentNaming
It would be better to fix the inconsistent naming rather than disable the warning

2023-01-16 11:48 UTC, AButler commented on Integration.Tests/Framework/Properties/Constants/TestDataConstants.cs
> +        // ReSharper disable once InconsistentNaming
It would be better to fix the inconsistent naming rather than disable the warning

2023-01-16 11:48 UTC, AButler commented on Integration.Tests/Framework/Shared/Objects/Clubware/Address.cs
> +#pragma warning disable CS8618
Can this be refactored so that it doesn't disable the warning? If this is an object just used for an API response it is best to remove the setter and add a constructor to set the values to make it immutable. Or even better make it a record.

2023-01-16 11:48 UTC, AButler commented on Integration.Tests/Framework/Shared/Objects/Clubware/PhoneNumber.cs
> +#pragma warning disable CS8618
Same as with the Address object, better to not remove the warning and to refactor.

2023-01-16 11:48 UTC, AButler commented on Integration.Tests/Framework/Shared/Objects/Clubware/UserDefinedFieldValue.cs
> +#pragma warning disable CS8618
Same as with the Address object, better to not remove the warning and to refactor.

2023-01-16 11:48 UTC, AButler commented on Integration.Tests/Framework/Shared/Objects/CoreAPI/Account/Account.cs
> +#pragma warning disable CS8618
Same as with the Address object, better to not remove the warning and to refactor.

2023-01-16 11:48 UTC, AButler commented on Integration.Tests/Framework/Shared/Objects/CoreAPI/Account/AccountDto.cs
> +#pragma warning disable CS8618
Same as with the Address object, better to not remove the warning and to refactor.

2023-01-16 11:48 UTC, AButler commented on Integration.Tests/Framework/Shared/Objects/CoreAPI/Branches/Branch.cs
> +#pragma warning disable CS8618
Same as with the Address object, better to not remove the warning and to refactor.

2023-01-16 11:48 UTC, AButler commented on Integration.Tests/Framework/Shared/Objects/Clubware/Address.cs
> +#pragma warning disable CS8618
e.g.
```c#
public class Address
{
    public Address(string type, string address1, string city, string postcode, string state, bool isPreferred)
    {
        Type = type;
        Address1 = address1;
        City = city;
        Postcode = postcode;
        State = state;
        IsPreferred = isPreferred;
    }

    public string Type { get; }
    public string Address1 { get;  }
    public string City { get; }
    public string Postcode { get; }
    public string State { get; }
    public bool IsPreferred { get; }
}
```

or

```c#
public record Address(
    string Type, 
    string Address1, 
    string City, 
    string Postcode, 
    string State, 
    bool IsPreferred
);
```

2023-01-16 11:48 UTC, AButler commented on Integration.Tests/Framework/Shared/Objects/Clubware/ClubwareMember.cs
> +#pragma warning disable CS8618
Same as with the Address object, better to not remove the warning and to refactor.

2023-01-16 11:48 UTC, AButler commented on Integration.Tests/Framework/Shared/Objects/Clubware/PartialClubwareMember.cs
> +#pragma warning disable CS8618
Same as with the Address object, better to not remove the warning and to refactor.

2023-01-16 11:48 UTC, AButler commented on Integration.Tests/Framework/Shared/Objects/CoreAPI/Member/MemberInfo.cs
> +    public record MemberInfo
Best to refactor this to use a record properly, by moving the properties to the constructor.

2023-01-16 11:48 UTC, AButler commented on Integration.Tests/Framework/Shared/Objects/CoreAPI/Member/MemberProfile.cs
> +    public record MemberProfile
Same as MemberInfo, refactor this to use a record constructor.

2023-01-16 11:48 UTC, AButler commented on Integration.Tests/Framework/Shared/Objects/CoreAPI/Other/CarRegistration.cs
> +#pragma warning disable CS8618
Same as with the Address object, better to not remove the warning and to refactor.

2023-01-16 11:48 UTC, AButler commented on Integration.Tests/Framework/Shared/Objects/CoreAPI/Payment/MemberPayment.cs
> +        public string Description { get; set; } = null!;
Same as with the Address object, better to not avoid the warning and to refactor.

2023-01-16 11:48 UTC, AButler commented on Integration.Tests/Framework/Shared/Objects/Templates/AddOnTemplate.cs
> +        public string MembershipType { get; set; } = null!;
Same as with the Address object, better to not avoid the warning and to refactor.

2023-01-16 14:08 UTC, AButler approved these changes

2023-01-16 15:36 UTC, merged